# Use true color (27-bit color) inside tmux
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -g status-position bottom
set -g base-index 1
set -g pane-base-index 1

# Your key remapping
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

# Smart pane switching with awareness of Vim splits
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

# Alt + number → switch windows
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9

# Prefix + number → switch sessions
bind-key 1 switch-client -t setup
bind-key 2 switch-client -t workspace
bind-key 3 switch-client -t dsa
bind-key 4 switch-client -t learning
bind-key 5 switch-client -t interview
bind-key 6 switch-client -t 6
bind-key 7 switch-client -t 7
bind-key 8 switch-client -t 8
bind-key 9 switch-client -t 9

set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes

# theming
set -g status-style bg=#000000,fg=#65D1FF
set -g status-justify centre
set -g status-left "#[bg=#F7768E, fg=#000000, bold] #S "
set -g status-left-length 100
set -g status-right-length 100
set -g status-right "\
#[fg=#E0AF68]#h \
#[fg=#7F9CCB, bold] %d-%b-%Y "
set -g window-status-format "#[bg=#000000, fg=#BB9AF7, bold] #I:#W "
set -g window-status-current-format "#[bg=#BB9AF7, fg=#000000, bold] #I:#W "
set -g window-status-separator ""


set -g @resurrect-capture-pane-contents 'on' # allow tmux-ressurect to capture pane contents
set -g @continuum-restore 'on' # enable tmux-continuum functionality
set -g @continuum-save-interval '1'

# --- Plugin Manager (TPM) ---
# tpm plugin
set -g @plugin 'tmux-plugins/tpm'
# This MUST be the very last line of your tmux.conf
run '~/.tmux/plugins/tpm/tpm'
